namespace TerminalMatrix.TerminalColor;

public enum ColorName
{
    Black,
    White,
    Red,
    Cyan,
    Violet,
    Green,
    Blue,
    Yellow,
    Orange,
    Brown,
    LightRed,
    DarkGrey,
    Grey,
    LightGreen,
    LightBlue,
    LightGrey,
    XtendedVeryDarkCyan,
    XtendedVeryLightGrey,
    XtendedDarkRed,
    XtendedDarkCyan,
    XtendedDarkViolet,
    XtendedDarkGreen,
    XtendedDarkBlue,
    XtendedDarkYellow,
    XtendedDarkOrange,
    XtendedDarkBrown,
    XtendedClearRed,
    XtendedVeryDarkGrey,
    XtendedMiddleGrey,
    XtendedVeryDarkGreen,
    XtendedMiddleBlue,
    XtendedDarkPaleGreen
}